### PR TITLE
Final

### PR DESCRIPTION
**Pull request by levaja**
In this PR only Week 5 is missing, but it will be added today (after that, it can be merged). Also, feel free to comment if you have any (final) remarks :)

### CODE REVIEW

**Comment by MrHug** [comment]
@levaja , can you add an "@MrHug" here when you've pushed Week5? Then I'll quickly go over them and merge the PR then :)

**Comment by levaja** [comment]
Of course, I will notify you :)

**Comment by Felienne** [comment]
@levaja Please mention me with an @ too, so I know when to pass them on to the Chinese translators. Thanks!

**Comment by levaja** [comment]
@MrHug and @Felienne , all subtitles are finally final now :)

**Pull request merged**
